##
# Run tests
##
name: Tests
on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v6

    - name: 'Bitrise Build Cache Activate for RN'
      env:
        BITRISE_BUILD_CACHE_AUTH_TOKEN: ${{ secrets.BITRISE_BUILD_CACHE_AUTH_TOKEN }}
        BITRISE_BUILD_CACHE_WORKSPACE_ID: ${{ vars.BITRISE_BUILD_CACHE_WORKSPACE_ID }}
      run: |
        #!/usr/bin/env bash
        set -euxo pipefail

        # download Bitrise Build Cache CLI
        curl --retry 5 -sSfL 'https://raw.githubusercontent.com/bitrise-io/bitrise-build-cache-cli/main/install/installer.sh' | sh -s -- -b /tmp/bin -d

        # run the CLI to enable Bitrise build cache for React Native
        /tmp/bin/bitrise-build-cache activate react-native

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v6
      with:
        node-version: 22

    - name: Setup repo
      shell: bash
      run: |
        #!/usr/bin/env bash
        set -euxo pipefail
        cp config.example.js config.js
        cat > ./android/app/src/main/res/values/config.xml <<'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <string name="gmaps_api_key">xxx</string>
        </resources>
        EOF
        npm install
        npm run add-example-model
    
    - run: bitrise-build-cache react-native run -- npx react-native build-android

    # - run: npm test

  notify:
    name: Notify Slack
    needs: test
    if: ${{ success() || failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: iRoachie/slack-github-actions@v2.3.0
        if: env.SLACK_WEBHOOK_URL != null
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BUILDS_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
